# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a06986addd0332e5d79e8f8367a28f8e5cfa924f9b684fcd8d3194937c83b8646b32d3400422b0ebe044d912bce21da2773a2f6ce3ad3cedf4aa8bc57a25ab0a

test:
  secret_key_base: 0d237e7900a99655106d0657e584b50c7b34d5e07dbcfe6233cbeac7b726857d6b04307099f5d15713767acfcff35fb1132edf6b09150f23a3cf8f0b10e52be0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
